enum EventName{
  updateUserCoin,
  updateTipsNum,
  updateUserHeartNum,
  updateUserLevel,
  updatePayType,
  showCheckInGuide,
  showWordBubbleGuide,
  showAnswerTips,
  showOldUserAnswerTips,
  updateBubbleNum,
  signSuccess,
  updateHomeIndex,
  startRotationWheel,
  stopRotationWheel,
  updateWheelChance,
}